#!/usr/bin/env bash
# pre-build.sh — Deploy InstructionSender contract and register extension on-chain.
#
# Inputs (env vars, typically set in .env):
#   ADDRESSES_FILE  — path to deployed-addresses.json (auto-detected if unset)
#   CHAIN_URL       — chain RPC URL (default: https://coston2-api.flare.network/ext/C/rpc)
#   PRIVATE_KEY     — funded private key (hex, no 0x prefix)
#   LOCAL_MODE      — true for local devnet, false for Coston2 (default: false)
#
# Outputs:
#   config/extension.env — EXTENSION_ID and INSTRUCTION_SENDER
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[pre-build]${NC} $*"; }
step() { echo -e "\n${CYAN}=== Step $1: $2 ===${NC}"; }
die()  { echo -e "${RED}[pre-build] ERROR:${NC} $*" >&2; exit 1; }

# --- Load .env from project root (if present) ---
if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

ADDRESSES_FILE="${ADDRESSES_FILE:-}"
# Resolve relative paths against PROJECT_DIR (not caller's cwd)
if [[ -n "$ADDRESSES_FILE" && "$ADDRESSES_FILE" != /* ]]; then
    ADDRESSES_FILE="$PROJECT_DIR/$ADDRESSES_FILE"
fi
CHAIN_URL="${CHAIN_URL:-https://coston2-api.flare.network/ext/C/rpc}"
CONFIG_OUTPUT="$PROJECT_DIR/config/extension.env"

# Auto-detect addresses file
if [[ -z "$ADDRESSES_FILE" ]]; then
    LOCAL_MODE="${LOCAL_MODE:-false}"
    if [[ "$LOCAL_MODE" != "true" ]]; then
        candidate="$PROJECT_DIR/config/coston2/deployed-addresses.json"
        if [[ -f "$candidate" ]]; then
            ADDRESSES_FILE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
        fi
    fi

    # Fall back to sim_dump candidates (local devnet)
    if [[ -z "$ADDRESSES_FILE" ]]; then
        for candidate in \
            "$PROJECT_DIR/../../e2e/docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../../docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../../../docker/sim_dump/deployed-addresses.json"; do
            if [[ -f "$candidate" ]]; then
                ADDRESSES_FILE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
                break
            fi
        done
    fi

    [[ -n "$ADDRESSES_FILE" ]] || die "Cannot find deployed-addresses.json. Set ADDRESSES_FILE."
fi

[[ -f "$ADDRESSES_FILE" ]] || die "Addresses file not found: $ADDRESSES_FILE"

# Resolve to absolute path so it works after cd into go/tools/
ADDRESSES_FILE="$(cd "$(dirname "$ADDRESSES_FILE")" && pwd)/$(basename "$ADDRESSES_FILE")"

log "Chain URL:      $CHAIN_URL"
log "Addresses file: $ADDRESSES_FILE"

# --- Step 1: Generate Go bindings from Solidity contract ---
step 1 "Generate Go bindings"
"$SCRIPT_DIR/generate-bindings.sh" || die "Binding generation failed"

# --- Step 2: Deploy InstructionSender ---
step 2 "Deploy InstructionSender contract"
cd "$PROJECT_DIR/go/tools"
INSTRUCTION_SENDER=$(go run ./cmd/deploy-contract -a "$ADDRESSES_FILE" -c "$CHAIN_URL" --verify=false 2>/dev/null | tail -1) || die "Deploy failed"
log "InstructionSender deployed at: $INSTRUCTION_SENDER"

# --- Step 3: Register extension ---
step 3 "Register extension on-chain"
EXTENSION_ID=$(go run ./cmd/register-extension -a "$ADDRESSES_FILE" -c "$CHAIN_URL" --instructionSender "$INSTRUCTION_SENDER" 2>/dev/null | tail -1) || die "Registration failed"
log "Extension ID: $EXTENSION_ID"

# --- Step 4: Write config ---
step 4 "Write config"
mkdir -p "$(dirname "$CONFIG_OUTPUT")"
cat > "$CONFIG_OUTPUT" <<EOF
# Auto-generated by pre-build.sh — do not edit manually
EXTENSION_ID=$EXTENSION_ID
INSTRUCTION_SENDER=$INSTRUCTION_SENDER
EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Pre-build complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo "  EXTENSION_ID         $EXTENSION_ID"
echo "  INSTRUCTION_SENDER   $INSTRUCTION_SENDER"
echo "  Config file          $CONFIG_OUTPUT"
