#!/usr/bin/env bash
# start-services.sh — Start the sign extension Docker Compose stack.
#
# Prerequisites:
#   - config/extension.env exists (created by pre-build.sh), OR EXTENSION_ID is set in .env
#   - .env is configured with PRIVATE_KEY, INITIAL_OWNER, LANGUAGE, etc.
#   - config/proxy/extension_proxy.toml exists with DB credentials
#
# Usage: ./scripts/start-services.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log() { echo -e "${GREEN}[start-services]${NC} $*"; }
die() { echo -e "${RED}[start-services] ERROR:${NC} $*" >&2; exit 1; }

# --- Load .env from project root (if present) ---
if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

# --- Load extension config (generated by pre-build.sh) ---
CONFIG_FILE="$PROJECT_DIR/config/extension.env"
if [[ -f "$CONFIG_FILE" ]]; then
    set -a
    source "$CONFIG_FILE"
    set +a
    log "Loaded config from $CONFIG_FILE"
fi

EXTENSION_ID="${EXTENSION_ID:-}"
[[ -n "$EXTENSION_ID" ]] || die "EXTENSION_ID not set. Run pre-build.sh first or set it in .env."

EXT_PROXY_URL="${EXT_PROXY_URL:-http://localhost:6676}"

log "Extension ID: $EXTENSION_ID"
log "Starting services with Docker Compose..."

cd "$PROJECT_DIR"
docker compose up -d --build || die "docker compose up failed"

# Wait for proxy to be ready
log "Waiting for extension proxy at $EXT_PROXY_URL/info ..."
elapsed=0
timeout=120
while ! curl -sf -o /dev/null "$EXT_PROXY_URL/info" 2>/dev/null; do
    elapsed=$((elapsed + 2))
    if [[ $elapsed -ge $timeout ]]; then
        die "Timed out after ${timeout}s waiting for extension proxy ($EXT_PROXY_URL)"
    fi
    sleep 2
done
log "Extension proxy is ready"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Services started (Docker Compose)${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${CYAN}Services${NC}"
echo "  redis, ext-proxy, extension-tee"
echo "  Proxy URL: $EXT_PROXY_URL"
echo ""
echo -e "${CYAN}Commands${NC}"
echo "  Logs:    docker compose logs -f"
echo "  Stop:    ./scripts/stop-services.sh"
